INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE) values (3, 'Diode', '', 10.0, 5, 'COMPONENT');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE) values (4, 'Transistors', '', 30.0, 1, 'COMPONENT');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE) values (5, 'Bipolar junction transistor', '', 40.0, 10,'COMPONENT');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE) values (6, 'Transistors', '', 10.0, 2, 'COMPONENT');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE) values (7, 'Diode', '', 25.0, 5, 'COMPONENT');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE) values (8, 'Transistors', '', 30.0, 10, 'COMPONENT');
UPDATE ITEM set AVAILABLE_QUANTITY = 2 where id < 3;
UPDATE ITEM set PRICE = 20.0 where id < 3;