DELETE FROM ITEM;
ALTER TABLE ITEM
ADD (IMAGE_URL varchar(200));
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (1, 'Arduino UNO Rev3', 'The board everybody gets started with, based on the ATmega328.', 3500, 34, 'COMPONENT', 'http://store.arduino.cc/bmz_cache/4/4578f41d9764a5c236470019f05dd2bc.image.229x182.jpg');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (2, 'Arduino Leonardo with Headers', 'Similar to an Arduino UNO, can be recognized by computer as a mouse or keyboard.', 3800, 4, 'COMPONENT', 'http://store.arduino.cc/bmz_cache/c/c6a035256a74209636f3aa19132f280f.image.229x182.jpg');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (3, 'Arduino YÚN', 'Arduino with onboard Wi-Fi connectivity and a Linux computer. Great for IoT projects.', 5600, 20, 'COMPONENT', 'http://store.arduino.cc/bmz_cache/3/378e52bca228df3a2221968e7c4fe83f.image.229x182.jpg');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (4, 'USB 2 Serial Converter (USB Mini)', 'Turns a USB connection to the 5V TX and RX Arduino requires to communicate.', 600, 44, 'COMPONENT', 'http://store.arduino.cc/bmz_cache/7/78e33063e7bb7ee89e76010a8ba8d790.image.447x354.jpg');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (5, 'Battery connector', 'Battery connector for 8 1v5 AA batteries with 9V battery plug', 130, 120, 'COMPONENT', 'http://store.arduino.cc/bmz_cache/0/002d16982de38a13e84b3a593013a3f0.image.447x354.jpg');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (6, 'ATMega328 - Microcontroller', 'This product let you to realize your small project without using a full size Arduino board. To make this microcontroller working with the Arduino IDE you need a 16Mhz crystal, a 5 V power supply and a serial connection.', 1400, 20, 'COMPONENT', 'http://store.arduino.cc/bmz_cache/9/9a9b5c9e479e1a5b237b41a173d34dcf.image.472x354.jpg');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (7, '10 Red LED 5mm', '10 Red Leds to bright up your projects.', 20, 300, 'COMPONENT', 'http://store.arduino.cc/bmz_cache/7/7bc665ff752f0d7e6567dee4bb284c82.image.446x354.jpg');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (8, 'Spark Photon', 'The Photon is a tiny Wi-Fi development kit for creating connected projects and products. It''s easy to use, it''s powerful, and it''s connected to the cloud. Does not ship with breadboard or USB cable.', null, 5, 'COMPONENT', 'https://www.filepicker.io/api/file/GRfBJYSMSgel7wOh4mwH');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (9, 'Spark Core', 'The Spark Core is a tiny Wi-Fi development kit based on Texas Instrument''s CC3000. We launched it on Kickstarter in 2013, and we''ve shipped tens of thousands of them', null, 3, 'COMPONENT', 'https://www.filepicker.io/api/file/tUmgVFDaRxioKUgCDxPZ');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (10, 'Ultra Sonic range measurement module', 'Seeed ultrasonic sensor is non-contact distance measurement module, which is also compatible with electronic brick. Its designed for easy modular project usage with industrial performance.', 1200, 3, 'COMPONENT', 'http://store.arduino.cc/bmz_cache/6/64a3a88291c5a6a54cb2dbb7a23b8a66.image.447x354.jpg');
INSERT into ITEM (ID, NAME, DESCRIPTION, PRICE, AVAILABLE_QUANTITY, TYPE, IMAGE_URL) values (11, 'BeagleBone Black', 'A true open hardware, community-supported embedded computer for developers and hobbyists. Ride the 1GHz edge with the Sitara™ ARM® Cortex-A8 processor, boot Linux in under 10 seconds and get started on development in less than 5 minutes with just a single USB cable.', 3100, 33, 'COMPONENT', 'http://beagleboard.org/static/ti/hp_black_sm.jpg');